NHSDigital/api-management-utils

- .flake8
- .gitignore
- apigee_client.py
- apigee_client_test.py
- poetry.lock
- pyproject.toml
- spec_uploader.py
This is a PR to enable the first two acceptance criteria of https://jira.digital.nhs.uk/browse/APM-531.
It makes a change to the portal deploy to add APIs to the production portals, but leave them unpublished for now. In future, we just flip the switch and they are ready to go.
I decided to clean up a little while I was in the codebase, too.
> APM-531 Allow setting visibility on create/update and general refactor

- spec_uploader.py
* Add pull request option to args so that it only deploys to specified environment
> Apm 815 pull request option

- env_cleaner.py
- env_cleaner_test.py
This change adds a flag `--respect_prs` to `env_cleaner.py`, which checks the public GitHub API for any open pull requests that match the name of a proxy deployed on apigee. Any proxies without pull requests are then acted upon, and vice versa.
Unit tests are included.
> APM-901 | Respect Open PR

- env_cleaner.py
Add support for EPS environments
> [AEA-260] Add electronic prescriptions to whitelist for env cleaner

- ansible/roles/deploy-apigee-proxy/tasks/main.yml
Changing to URI broke this -- fixing it here.
> APM-1162 Fix bad set_fact

- Makefile
- ansible/roles/deploy-apigee-product/vars/main.yml
- apigee_client.py
- apigee_client_test.py
- env_cleaner.py
- env_cleaner_test.py
- poetry.lock
- pyproject.toml
- scripts/template.py
- spec_uploader.py
This dict is used when deploying products to translate their name to a friendlier version. Dev was missing and this became apparent when trying to deploy.
> APM-882 Fix missing Development key

- azure/common/pr.yml
Do not forward fully qualified service name
> APM 1213 Add missing template param

- azure/templates/deploy-service.yml
Removes a condition on a step that should always run
> APM-1313 Remove condition on installing prereqs

- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/deploy-stages.yml
- azure/common/pr.yml
- azure/common/release.yml
Don't depend on a variable for build references
> Apm 1162 fix build refs

- .gitignore
- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/pr.yml
- azure/common/release.yml
- azure/templates/deploy-service.yml
This adds superior mechanism for custom jinja templating in the deployment pipeline as required by identity service
----
#
> APM-1324 Add jinja_templates as a pipeline parameter

- azure/common/apigee-deployment.yml
- azure/common/deploy-stages.yml
This allows proxy_path to be overwritten on a per-environment basis
----
#
> APM-1347 Add proxy_path to list of scoped variables

- ansible/roles/bootstrap-project/tasks/main.yml
Rename variables to bring inline with common pipelines and add files to template
> Apm 1214 template api

- azure/common/apigee-build.yml
> APM-1316 Add new stepList in to be executed post ECS proxy pushing

- azure/common/deploy-stage.yml
- azure/common/pr.yml
> APM-1316 Only notify for PRs, not releases

- azure/common/deploy-stages.yml
- azure/common/pr.yml
This should give live/sandbox proxies different names in apigee.
----
#
> APM-1386 Add `proxy_path` to `fully_qualified_service_name` in PRs

- azure/common/deploy-stage.yml
> APM-0000 Hotfix environment variable name

- azure/templates/deploy-service.yml
In preparation for a bit of python...
----
#
> APM-991 Include python in template list

- azure/common/deploy-stage.yml
Step failing due to `"` in commit message. This step is debug only and arguably should not have been in here anyway.
> APM-1162 Remove failing debug step

- azure/templates/deploy-service.yml
See https://nhsd-jira.digital.nhs.uk/browse/APM-1311?focusedCommentId=684805&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-684805
> Don't find template hooks that are substrings of one another

- azure/templates/deploy-service.yml
> missed an asterisk..

- azure/templates/deploy-service.yml
> APM-0000 Hotfix deploy

- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
> APM-0000 Set default value of API product files when no folder

- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
> APM-0000 Set default value for api_products too

- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
> APM-0000 Remove reference to api_product_files from fail_msg

- ansible/deploy-apigee-product-and-spec.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-product.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-spec.yml
- azure/templates/deploy-service.yml
> Fix pipeline

- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-spec.yml
> Boolify SPEC_FILE

- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-spec.yml
> Set spec_id to null by default

- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-spec.yml
> Fix variable names

- azure/common/deploy-stage.yml
- azure/components/update-github-status.yml
Make reporting environment specific. Stops reporting of success if one environment fails.
> Apm 1512 GitHub reporting

- azure/common/apigee-build.yml
- azure/components/update-github-status.yml
Add notify option to the build pipeline.
> Apm 1523 build reporting

- azure/components/update-github-status.yml
Warn on bad github statuses instead of killing the run.
> Apm 1162 GitHub status warn on fail

- azure/common/deploy-stage.yml
- azure/components/get-aws-secrets-and-ssm-params.yml
- azure/components/set-facts.yml
* Make each line of multiline secret into a var
> Apm 1509 multiline secret

- azure/components/get-aws-secrets-and-ssm-params.yml
- azure/components/set-facts.yml
Reverts NHSDigital/api-management-utils#113
https://nhsdigital-platforms.slack.com/archives/G016JRWN6AY/p1603810401004900
> Revert "Apm 1509 multiline secret"

- azure/common/apigee-build.yml
Reverts NHSDigital/api-management-utils#115
> Revert "APM-000-hotfix"

- ansible/roles/deploy-apigee-proxy/tasks/main.yml
Adds a fix for working around the no_log being set to true, whilst still not revealing sensitive data
> APM-1400 Improve Ansible debug messages

- azure/components/get-aws-secrets-and-ssm-params.yml
Fixes re-run azure-pr-pipeline builds
> AMB-339 Fix for failing PR pipeline build

- azure/components/get-aws-secrets-and-ssm-params.yml
* Set defaults for parameters so it doesn't fail on steps where nothing is provided to the parameter when explicitly set.
> APM-000 Add defaults to parameters for ssm

- azure/components/get-aws-secrets-and-ssm-params.yml
> Add --with-decryption flag to aws ssm get-parameter call

- ansible/library/filter_api_products.py
- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
For increasing rate limit on prod in the PDS api
> APM-1553 Customisable products by environment

- ansible/remove-old-pr-portal-apis.yml
- ansible/roles/remove-old-pr-portal-apis/tasks/main.yml
- ansible/roles/remove-old-pr-specs/tasks/main.yml
Converts query search of the json brought back from apigee to a list of queries for flexible searching of old prs
> APM-1624 Add extra queries to json_query search

- ansible/Makefile
- ansible/deploy-ecs-proxies.yml
- ansible/roles/deploy-ecs-proxies/tasks/main.yml
- azure/templates/deploy-service.yml
This reverts commit 672d1a6144785030f4086b150e478adf3b8e047e.
----
#
> Revert "apm-1552: release release_info var"

- azure/templates/deploy-service.yml
> APM-1162 hotfix deploy order

- ansible/Makefile
- ansible/deploy-ecs-proxies.yml
- ansible/roles/deploy-ecs-proxies/tasks/main.yml
- azure/templates/deploy-service.yml
This reverts commit 9fa8fbc866225f13ccfc91ee3c1d24027e23de3e.
> Revert "Revert "apm-1552: release release_info var""

- .github/workflows/tests.yaml
- Makefile
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/apply_pull_request_namespace.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/validate_manifest.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/apigee/product.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/apigee/spec.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/apigee.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/apigee_environment.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/apigee_manifest.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/meta.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/ansible/test_correct_namespace.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/test_meta.py
- ansible/deploy-manifest.yml
- ansible/template-manifest.yml
- ansible/validate-manifest.yml
Also add automated unit tests of the ansible collection
----
#
> APM-1555 Add Aubyn's metadata collection to manifest

- ansible/Makefile
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/apply_pull_request_namespace.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/validate_manifest.py
- ansible/deploy-manifest.yml
> Fix ApplyPullRequestNamespace args

- ansible/roles/build-ecs-proxies/tasks/main.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-product-and-apidoc.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
- ansible/roles/deploy-apigee-proxy/tasks/main.yml
> apm-1351: retry behaviours for uri commands

- ansible/roles/build-ecs-proxies/tasks/main.yml
- ansible/roles/build-ecs-proxies/tasks/set-repository-policy.yml
- ansible/roles/build-ecs-proxies/vars/main.yml
> apm-1598: grant cross account policy for ecr repos

- ansible/roles/build-ecs-proxies/tasks/set-repository-policy.yml
- ansible/roles/create-ecr-build-user/vars/main.yml
> apm-1598: correct repository name and allow set repository policy

- ansible/roles/build-ecs-proxies/tasks/main.yml
- ansible/roles/build-ecs-proxies/vars/main.yml
- ansible/roles/create-ecr-build-role/vars/main.yml
- ansible/roles/create-ecr-build-user/vars/main.yml
> apm-1598: fixes to allow anisble ssm access

- azure/cleanup-pr-portal-apis-and-specs.yml
> apm-1351: bugfix spec cleanup

- ansible/deploy-manifest.yml
> APM-1646 manifest hotfix finish var rename

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_api_catalog_item.py
> APM-1646 manifest hotfix 2

- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-product-and-apidoc.yml
* :warning: fixes retries on  createdoc
> apm-1733: disable retries on create doc

- azure/common/deploy-stage.yml
- azure/templates/deploy-service.yml
> APM-1598 Use apm_prod for terraform apigee environment == 'prod'

- azure/common/deploy-stage.yml
> Fix inversion

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
> apm-1600: allow passrole on autoscaling

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
* :sparkles: allow assume role x-account
> apm-1598: allow deploy user assume role x-account

- azure/common/deploy-stage.yml
- azure/components/aws-assume-role.yml
Brings assume-role into line with api-management-infrastructure
> APM-1594 Fix role assumption

- ansible/create-build-env-vars.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
- azure/common/apigee-build.yml
- azure/common/deploy-stage.yml
- azure/create-build-env-vars.yml
- azure/templates/deploy-service.yml
> apm-1717: add ansible_color=yes to ansible tasks

- ansible/roles/build-ecs-proxies/tasks/main.yml
> apm-1717: new_repos needed

- ansible/roles/deploy-apigee-product-and-spec/tasks/update-api-doc.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/update-snapshot.yml
> Apm 1733 fix apidoc deploy

- ansible/roles/deploy-api-pipelines/tasks/main.yml
- Add --allow-no-subscriptions flag, which is the case for my user.
- Don't try to log in to azure when already logged in.
> APM-1162 Improve deploy-api-pipelines script

- azure/common/apigee-deployment.yml
- azure/common/deploy-manual-approval.yml
- azure/common/pr.yml
- azure/common/release.yml
Also remove option of setting manual approval on PR pipeline because
it doesn't make any sense.
> APM-1162 Explicitly set dependsOn for manual approval stage

- ansible/collections/ansible_collections/nhsd/apigee/roles/add_apim_guids_policy/tasks/main.yml
> APM-1162 Allow deprecated of meta w/ api.id instead of api.guid

- ansible/Makefile
- ansible/add-jwks-resource-url-to-app.yml
- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/add_jwks_resource_url_to_app.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_product.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/add_jwks_resource_url.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/deploy_api_catalog_item.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/deploy_product.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/deploy_spec.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/utils.py
- ansible/collections/ansible_collections/nhsd/apigee/roles/add_jwks_resource_url_to_app/tasks/main.yml
- ansible/collections/ansible_collections/nhsd/apigee/roles/add_jwks_resource_url_to_app/vars/main.yml
Now you don't have to log into apigee to put the jwks-resource-url onto an app.
> APM-1162 Add role to add jwks-resource-url to app

- ansible/Makefile
- ansible/collections/ansible_collections/nhsd/apigee/roles/add_jwks_resource_url_to_app/vars/main.yml
Slight easing of the interface
> APM-1162 No APIGEE_ORGANIZATION for add-jwks-resource-url-to-app

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/deploy_api_catalog_item.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/deploy_spec.py
> APM-1162 Fix missing import

- ansible/cleanup-proxy-for-env.yml
- ansible/create-api-deployment-pre-reqs.yml
> mm: remove unused roles

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/terraform.tf
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/destroy-ecs-proxies/templates/terraform/terraform.tf
> mm-1865: need > v3 of aws provider to support profiles too

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/.terraform.lock.hcl
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/versions.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/.terraform.lock.hcl
- ansible/roles/deploy-ecs-proxies/templates/terraform/terraform.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/versions.tf
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/.terraform.lock.hcl
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/versions.tf
- ansible/roles/destroy-ecs-proxies/templates/terraform/.terraform.lock.hcl
- ansible/roles/destroy-ecs-proxies/templates/terraform/terraform.tf
- ansible/roles/destroy-ecs-proxies/templates/terraform/versions.tf
- azure/_deprecated-become-build-user.yml
- azure/build-prereqs.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
- azure/common/apigee-build.yml
- azure/templates/deploy-service.yml
> Mm apm 1865 terraform 14 upgrade

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/.terraform.lock.hcl
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/versions.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/.terraform.lock.hcl
- ansible/roles/deploy-ecs-proxies/templates/terraform/terraform.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/versions.tf
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/.terraform.lock.hcl
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/terraform.tf
- ansible/roles/destroy-api-deployment-pre-reqs/templates/terraform/versions.tf
- ansible/roles/destroy-ecs-proxies/templates/terraform/.terraform.lock.hcl
- ansible/roles/destroy-ecs-proxies/templates/terraform/terraform.tf
- ansible/roles/destroy-ecs-proxies/templates/terraform/versions.tf
- azure/_deprecated-become-build-user.yml
- azure/build-prereqs.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
- azure/common/apigee-build.yml
- azure/templates/deploy-service.yml
> pull in tf 14 upgrade

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/add_jwks_resource_url_to_app.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/utils.py
Look up developer details from app developerId attribute.
Use that developer's email address to construct path to app attributes for POST request.
> APM-1873 Fix developer lookup

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_spec.py
> APM-1162 Hotfix spec workaround

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/constants.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/meta.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/test_meta.py
> Update list of spec guids

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/constants.py
> AEA-1177: Rename Signing Service to match existing proxies and products.

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/constants.py
> Fix signing service name

- azure/templates/deploy-service.yml
AMB-527 Removed unnecessary prod env prefix from prod url, as this is…
> AMB-527-RFC-30025111-Merge-fix-to-edge

- ansible/bootstrap-project.yml
- ansible/roles/bootstrap-project/tasks/main.yml
* Update ansible to template manifest
> APM-1706 Update template script to template manifest

- ansible/ansible.cfg
^^^ Does exactly what it says...
> APM-1162 Make ansible output legible

- azure/common/apigee-build.yml
- azure/templates/deploy-service.yml
Add validation step in build pipeline
-------
> APM-1162 Validate manifest in build pipeline

- ansible/roles/bootstrap-project/tasks/main.yml
* Update template bootstrap to fix issues
* Bump codegen version
> APM-1910 Update template bootstrap

- ansible/Makefile
- ansible/template-proxies.yml
- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/pr.yml
- azure/common/release.yml
- azure/templates/deploy-service.yml
> apm-1926: add support for a hosted target healthcheck

- ansible/Makefile
- ansible/roles/bootstrap-project/tasks/main.yml
- ansible/template-proxies.yml
- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/pr.yml
- azure/common/release.yml
- azure/templates/deploy-service.yml
> pull into edge

- ansible/roles/bootstrap-project/tasks/main.yml
> APM-1910 remove codegen and add more file to template

- azure/common/apigee-build.yml
> apm-1926: remove check licences

- ansible/roles/bootstrap-project/tasks/main.yml
* add template files and remove redundant ones
> APM-1910 Add template files and remove redundant ones

- ansible/roles/template-proxies/tasks/main.yml
> apm-1926: get account ids in templating

- ansible/roles/deploy-ecs-proxies/tasks/main.yml
- ansible/roles/template-proxies/tasks/main.yml
> apm-1926: make account ids available in ecs deploy too

- ansible/Makefile
- ansible/remove-old-auto-apps.yml
- ansible/roles/remove-old-auto-apps/tasks/main.yml
- ansible/roles/remove-old-auto-apps/vars/main.yml
- ansible/roles/remove-old-pr-products/tasks/main.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
> apm-xx: cleanup older auto apps

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/add_jwks_resource_url_to_app.py
Use expand=true to get all developer details, remove need for API successive calls to apigee.
> APM-2002 cache developer details between successive tasks

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_api_catalog_item.py
* Update snapshot on manifest deployment
> APM-2045 Update snapshot on manifest deployment

- azure/common/apigee-deployment.yml
- azure/common/deploy-stages.yml
> APM-2060 Add secret_file_ids to per-environment scoping list

- azure/common/deploy-stage.yml
- azure/templates/deploy-service.yml
* Use stage name for monitoring instead of environment
> APM-2016 Use stage name for key value for monitoring

- azure/templates/deploy-service.yml
* Use stage name instead of environment
> APM-2213 Use stage name instead of environment

- azure/cleanup-pr-portal-apis-and-specs.yml
> APM-2016 Reduce retain auto apps hours

- ansible/template-proxies.yml
> apm-2214: support jinja template configuration of suffix

- ansible/template-proxies.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
> Support jinja template configuration of suffix

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/apigee/product.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/test_product.py
> APM-2211 Add execption list to manual approval override

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/add_jwks_resource_url.py
> APM-2156 swap base url for jwks endpoint

- ansible/Makefile
- ansible/remove-old-auto-products.yml
- ansible/roles/remove-old-auto-products/tasks/main.yml
- ansible/roles/remove-old-auto-products/vars/main.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
> Apm 1925 remove old auto products

- azure/templates/deploy-service.yml
* Replace stage name underscore with hyphen for consistency
> APM-2241 Replace underscore with hyphens

- azure/templates/deploy-service.yml
> APM-2241 Use single quotes

- azure/components/curl.yml
> APM-2241 Use double quotes for body

- azure/components/curl.yml
- azure/templates/deploy-service.yml
> Apm 2241 Revert Changes

- azure/templates/deploy-service.yml
* Replace underscores in with hyphens
> APM-2241 Replace underscores in with hyphens

- azure/components/curl.yml
- azure/templates/deploy-service.yml
Fix the monitoring stage name to fix bug
> Fix Monitoring stage name

- scripts/purge_incorrect_env_vars.py
> Apm 2241 fix incorrect monitoring env data

- ansible/roles/remove-old-pr-proxies/tasks/remove-api.yml
- ansible/roles/remove-old-pr-proxies/tasks/undeploy-revision.yml
- azure/cleanup-pr-portal-apis-and-specs.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2326
> APM-2326 Add retries to undeploy revisions to avoid apigee failures

- azure/common/deploy-stage.yml
> AMB-779 fix service path override

- azure/common/pr.yml
> APM-2409 Add default manual approval to params

- azure/common/apigee-deployment.yml
- azure/common/deploy-manual-approval.yml
- azure/common/deploy-stages.yml
- azure/common/pr.yml
- azure/common/release.yml
> APM-2409 Add manual_approval_env overwrite

- azure/templates/deploy-service.yml
Reverts NHSDigital/api-management-utils#337
> Revert "AMB-783 Refactor monitoring by default feature"

- azure/templates/deploy-service.yml
- scripts/test_pull_request_deployments.py
> AMB-783 Added code from previous pull (337)

- azure/templates/deploy-service.yml
> AMB-783 Changed wording from 'dont' to 'doesn't' to correct grammer

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/add_jwks_resource_url_to_app.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/utils.py
The Apigee Edge API for developers will only return 1000. Now we have
more than that we need to adjust our use of the API to make sure we
have them all.
> APM-2016 Handle case when more than 1000 developers to check

- azure/templates/deploy-service.yml
> Amb 783 fix monitoring by default 503 status response when deployed hosted target proxy

- azure/templates/deploy-service.yml
> AMB-783 fixed if condition for _ping and _status checks

- ansible/roles/create-ecr-build-role/tasks/main.yml
> apm-2476: stop build role assume role policy updating on every build

- ansible/roles/create-ecr-build-role/tasks/main.yml
- azure/templates/deploy-service.yml
> merge from master

- ansible/roles/deploy-ecs-proxies/templates/terraform/fargate.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/locals.tf
> mm: apm add more custom tags to ECS services

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
> fix to allow ecs services to add / remove resource tags

- ansible/roles/remove-old-pr-proxies/tasks/remove-api-product.yml
Prevents issue linked [0] which causes a command to fail due to illegal characters in the url
[0] https://dev.azure.com/NHSD-APIM/API%20Platform/_build/results?buildId=47639&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=9118219c-a609-5d35-0e5a-3a0a4420add5
> APM-2348 urlencode product slugs

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/apigee/product.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/apigee/rate_limiting_config.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/manifest/meta.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/conftest.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/schema_versions/v1.1.2.json
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/test_product.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/test_ratelimiting_config.py
> APM-2016 Add special handling for 'ratelimiting' product attribute

- ansible/roles/create-api-deployment-pre-reqs/tasks/main.yml
- ansible/roles/deploy-ecs-proxies/tasks/main.yml
- ansible/roles/destroy-api-deployment-pre-reqs/tasks/main.yml
- ansible/roles/destroy-ecs-proxies/tasks/main.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2545
> APM-2545 Add expiry time to terraform lock on ECS container deploys

- azure/common/deploy-manual-approval.yml
> Update VM image for manual approval to ubuntu-latest.

- ansible/roles/remove-old-pr-portal-apis/tasks/main.yml
- ansible/roles/remove-old-pr-portal-apis/tasks/remove-pr-portal-api.yml
- ansible/roles/remove-old-pr-portal-apis/vars/main.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2707
> APM-2707 fix portal api clean up

- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_api_catalog_item.py
- ansible/collections/ansible_collections/nhsd/apigee/plugins/action/deploy_spec.py
> Merge in weaker spec requirement

- ansible/roles/build-ecs-proxies/tasks/build-container.yml
> APM-2590 use host network for docker build pipeline

- ansible/roles/build-ecs-proxies/tasks/build-container.yml
> APM-0000 Comment out network:host change

- ansible/remove-old-ecs-pr-deploys.yml
- ansible/roles/remove-old-ecs-pr-deploys/tasks/remove-ecs-deployment.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/components/aws-assume-role.yml
- azure/components/cleanup-ecs-pr-proxies-job.yml
> APM-3392 retry on role timeout

- ansible/roles/remove-old-ecs-pr-deploys/tasks/remove-ecs-deployment.yml
- azure/components/aws-assume-role.yml
> Increase assume role timeout

- ansible/remove-old-ecs-pr-deploys.yml
- ansible/roles/remove-old-ecs-pr-deploys/tasks/remove-ecs-deployment.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/components/aws-assume-role.yml
> Set expiration condition on ecs pr pipeline

- ansible/roles/remove-old-ecs-pr-deploys/tasks/remove-ecs-deployment.yml
> APM-3392 Increase minimum aws role duration remaining

- Makefile
- azure/components/cleanup-ecs-pr-proxies-job.yml
- poetry.lock
- pyproject.toml
- scripts/terraform_force_unlock.py
> Dp force unlock

- azure/components/aws-assume-role.yml
> APM-0000 Allow 'dev' to be account in aws-assume-role.yml

- ansible/roles/remove-old-ecs-pr-deploys/tasks/remove-ecs-deployment.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/components/cleanup-ecs-pr-proxies-job.yml
> APM-3869 Fix ECS clean up pipeline again

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/locals.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/outputs.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/alb.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/fargate.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/locals.tf
- azure/common/apigee-build.yml
- azure/templates/deploy-service.yml
Reverts NHSDigital/api-management-utils#447
> Revert "ALB changes"

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/locals.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/outputs.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/alb.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/fargate.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/locals.tf
- azure/common/apigee-build.yml
- azure/templates/deploy-service.yml
Reverts NHSDigital/api-management-utils#450
> Revert "Revert "ALB changes""

- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/iam.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/locals.tf
- ansible/roles/create-api-deployment-pre-reqs/templates/terraform/outputs.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/alb.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/fargate.tf
- ansible/roles/deploy-ecs-proxies/templates/terraform/locals.tf
- azure/common/apigee-build.yml
Reverts NHSDigital/api-management-utils#442
> Revert "APM-4363 changes to support ALB sharding"

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/utils.py
- ansible/collections/ansible_collections/nhsd/apigee/roles/deploy_manifest/tasks/main.yml
Attempts to fix API deployments by adding pagination support onto `get_all_apidocs`.
> Get API request pagination

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/utils.py
- ansible/collections/ansible_collections/nhsd/apigee/roles/deploy_manifest/tasks/main.yml
> APM-4806: Fix for pagination, and workaround to disable API catalogue entry creation in NHSD-NONPROD

- azure/templates/deploy-service.yml
> remove evil little typo

- azure/templates/deploy-service.yml
> another typo

- azure/templates/deploy-service.yml
> Apm 000 fix version parsing

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/models/ansible/validate_manifest.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/ansible/test_correct_namespace.py
- ansible/collections/ansible_collections/nhsd/apigee/tests/unit/plugins/module_utils/models/manifest/schema_versions/v1.1.8.json
Linked to https://github.com/NHSDigital/organisation-data-service-fhir-api/pull/74
> APM-5171 allow numbers in Apigee namespacing

- ansible/collections/ansible_collections/nhsd/apigee/roles/deploy_manifest/tasks/main.yml
> APM-000: Temporary spec deploy patch

- azure/common/apigee-build.yml
- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/deploy-stages.yml
- azure/common/pr.yml
- azure/common/release.yml
> APM-5855 make agent pool configurable for testing

- poetry.lock
- pyproject.toml
- upgrade py-docker to 7.1.0 to avoid https://github.com/docker/docker-py/issues/3256
> upgrade py-docker

- ansible/roles/deploy-ecs-proxies/vars/main.yml
- rollback setting default desired capacity
> rollback setting capacity

- ansible/roles/deploy-ecs-proxies/vars/main.yml
- scripts/test_pull_request_deployments.py
- use correct syntax for setting desired capacity
> correct syntax for setting desired capacity

- .github/workflows/continuous-integration.yml
- azure/templates/deploy-service.yml
- scripts/test_pull_request_deployments.py
- scripts/trigger_pipelines.py
> APM-2488 Update deployment tests to use SP

- poetry.lock
- pyproject.toml
> APM-6129-DependabotBalckIssueFix

- .github/workflows/sbom.yml
- scripts/create-sbom.sh
- scripts/update-sbom.py
> sbom configuration
