- .gitignore
- apigee_client.py
- env_cleaner.py
- env_cleaner_test.py
Adding in a script that can clean up crud that has built up over time.
Here's an example usage (undeploy sandbox proxies, i.e. the ones that have been tying up hosted targets):
```bash
$ poetry run python env_cleaner.py nhsd-nonprod internal-dev --proxies --sandbox-only --access-token=`cat .access_token` --undeploy-only
```
Here's the help text:
```
env_cleaner.py
A tool for cleaning up apigee-envs
Usage:
spec_uploader.py <apigee_org> <apigee_env> --access-token=<access_token> [--specs] [--proxies] [--products] [--sandbox-only] [--dry-run] [--min-age=<min_age>] [--undeploy-only]
spec_uploader.py (-h | --help)
Options:
-h --help                      Show this screen
--access-token=<access_token>  Apigee access token to authorise requests
--specs                        Prune specs
--proxies …
```
> APM-901 Env cleaning process

- spec_uploader.py
incorrect name meaning no callback url can be specified during developer app registration
> BUGFIX: apm-1042

- ansible/deploy-apigee-proxy.yml
- ansible/roles/deploy-apigee-proxy/tasks/main.yml
- ansible/roles/deploy-apigee-proxy/vars/main.yml
This change is a dumb deploy of proxies and the new proxy revisions they create; by that, I mean that if the same proxy is already deployed, it will be written over regardless. I'll split that improvement out into a new ticket to take up later.
This will replace part of the terrraform currently in use in the deploy-service task. Ideally we will want to replace all of it at some point, so I will create another ticket for that work.
> APM-1100: Upload and deploy proxies with ansible

- ansible/deploy-apigee-proxy.yml
- ansible/roles/deploy-apigee-proxy/tasks/main.yml
Some proxies don't have ping yet, and the deploy was dying with an unhelpful error: https://dev.azure.com/NHSD-APIM/API%20Platform/_releaseProgress?_a=release-environment-logs&releaseId=2328&environmentId=8629
> APM-1100 Allow skipping _ping step and fail if a ping fails

- azure/common/deploy-stage.yml
- azure/common/pr.yml
- azure/components/update-github-status.yml
- azure/templates/deploy-service.yml
Adds:
* `notify` flag to toggle github notifying behaviour
* Fetching `COMMIT_SHA` by parsing it from `$(Build.SourceVersionMessage)` [0]
* Changes the github notify template to use `COMMIT_SHA` instead of `$(Build.SourceVersion)` [0]
* Change the `displayName` of the github notify template to make more sense
[0] This has to be done because `$(Build.SourceVersion)` is the commit hash of the _merge commit_, i.e. the commit that will be created when the branch is merged. GitHub status reporting uses the commit hash of the top commit of a branch, or the `head`. Azure pipeline does not provide an easy way to access this head commit hash value, but it is included in the `$(Build.SourceVersionMessage)`, which takes the form of `Merge abc in to xyz` -- and we want `abc`.
> APM-1162 Re-add reporting to github for PRs

- ansible/roles/deploy-apigee-proxy/tasks/main.yml
- azure/common/apigee-build.yml
- azure/common/deploy-stage.yml
- azure/templates/deploy-service.yml
* Uses only the 'common' utils resource (all explicit clones have been removed and all non-common utils clones have been taken out)
* Utils is copied into the build artifact near the end of the build
* Utils is then used directly from the artifact in prs and releases
* Fixed the PING condition in the proxy deploy ⚠️ this may cause some deploys where a ping is NOT desired to fail. It should not affect deploys where a ping is desired.
> APM-1356 Use 'common' resource everywhere we need utils and place utils in the build artifact

- azure/common/apigee-build.yml
* Doesn't copy across .venv when copying utils into the artifact, preventing a issue in deploys
> APM-1162 Don't copy accross .venv

- azure/common/apigee-deployment.yml
- azure/common/deploy-stages.yml
The azure pipline template expansion seems to have a notion of a
"current directory" and "current repository". In the case that the
stepLists are templated before extending the common pipeline yaml.
However, in the scoped case, the template expansion happens in the
common repository itself. So unless the user specifies a repo, we
tweak the value string associated with the 'template' key so the path
relative to azure/ in the 'self' repo.
This means the behaviour of paths are the same whether or not the hook
is defined at a global or per-environment scope.
----
#
> APMSPII-376 Add per-environment hooks _scoped_pipeline_vars

- azure/common/apigee-build.yml
This is possible now because of a change to the common 'update github status' step, which now will warn instead of fail when the COMMIT_HASH is not properly set.
It appears that azure devops has totally given up on trying to give us status updates anymore, so this change is required to get this working again.
> APM-1162 Enable build notifications by default

- azure/common/apigee-build.yml
This is for possible future changes -- adding utils version so we can either enforce match or use matching version.
> APM-1162 Dump utils pipeline version in artifact

- ansible/roles/deploy-apigee-product-and-spec/tasks/deploy-product-and-apidoc.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/main.yml
* Use service instead of product name on pull requests, so its easier to determine PR products from release
> APM-1694 Use service name on PR's as product names

- azure/components/curl.yml
- azure/templates/deploy-service.yml
* Just use the internal-dev monitoring service for everything for now, until we have a separate prod instance
* Don't include env name when prod to prevent `prod.api...` from happenning
> APM-1162 Fix auto-enrolment to monitoring for production services

- ansible/roles/deploy-apigee-product-and-spec/tasks/create-api-doc.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/update-api-doc.yml
- ansible/roles/deploy-apigee-product-and-spec/tasks/update-snapshot.yml
* Streamline validation for api docs
* only check all apidocs for duplicates if a 500 is returned from apigee
> APM-1733 Only check all apidocs on a 500 request and streamline

- azure/common/apigee-deployment.yml
- azure/common/deploy-stage.yml
- azure/common/release.yml
remove dev as deployment environment since apis-dev ECS cluster no longer exist
> APM-1701 remove dev as deploy environment

- ansible/roles/bootstrap-project/tasks/main.yml
* Adds checks in for required vars and fails early if they are not present
* Fall back to meta, which is what is actually in use
* Doc updates: https://nhsd-confluence.digital.nhs.uk/display/APM/API+repository+template
> APM-1162 Fix bootstrapping process

- azure/templates/deploy-service.yml
Ensures the AWS context is changed back to the APIM default after pre_template steps have been run
> Swap back to default role after pre_template

- ansible/Makefile
CHECK=1 will trigger check mode, CHECK=0 (or anything else) will not.
> APM-2002 Smarter CHECK/VERBOSE flags

- azure/common/apigee-deployment.yml
- azure/common/deploy-stages.yml
- azure/common/release.yml
This topic came up in the release process retro on 28/01/2022.
The scope is for example API Producer
Acceptance Criteria
Exemplar producer team has its own manual approval environment 
Azure DevOps team was created to manage this, which includes producer team members only
Azure DevOps team + platform admins set as approvers on manual approvals environment
Common pipelines configured to allow API-specific manual approval environs on prod
The producer environment can't be overwritten
Producer zone
first time into the production section on setting up self-approval
Any changes to release management pages
KOP on how to set up team/env and users
Manually tested with Canary API
> APM-2321 add producer manual approval for prod

- ansible/collections/ansible_collections/nhsd/apigee/plugins/module_utils/paas/urls.py
- azure/common/deploy-stage.yml
Api registry data has been copied from ptl dynamo db table to prod dynamo db table. This PR is to update where Utils pulls its values from.
> Update urls to point at prod

- ansible/roles/remove-old-ecs-pr-deploys/vars/main.yml
- azure/cleanup-ecs-pr-proxies.yml
- azure/components/cleanup-ecs-pr-proxies-job.yml
- scripts/terraform_force_unlock.py
> APM-3095 run ecs cleanup on 2 day retain hours

- azure/components/set-facts.yml
> APM-4219 Sort by latest to bring back artifact by time

- ansible/template-proxies.yml
The `HOSTED_TARGET_CONNECTION_PATH_SUFFIX` variable is referenced for constructing the path value within the `HOSTED_TARGET_CONNECTION` variable.
This variable was not instantiated from the environmental variable that holds the value that has been configured within your API-M pipelines/variables.
The same issue was affecting `HOSTED_TARGET_HEALTHCHECK_SUFFIX`.
This PR adds the instantiation of these values from env within template-proxies.yml.
> HOSTED_TARGET_CONNECTION_PATH_SUFFIX passing to proxy templates

- ansible/template-proxies.yml
- azure/common/apigee-deployment.yml
- azure/common/pr.yml
Moves the default value for the `host_target_healthcheck_suffix` value to being defined within the pipeline definitions rather than in ansible.
This attempts to correct a bug introduced with https://github.com/NHSDigital/api-management-utils/pull/438.
The previous PR allowed this value to be configurable - where as before it was always resolving to the defaulted `/_status` within the ansible variable `HOSTED_TARGET_HEALTHCHECK` - it was defaulting to the value of an empty string. If you configured the `host_target_healthcheck_suffix` variable within your pipelines to `/_status` then this would not cause you issues.
> host_target_healthcheck_suffix defaults

- azure/common/apigee-build.yml
Makes the installed python version configurable, leaving 3.8 as the default so as to not make this a breaking change.
> BAU-14135: Make python version configurable in build
